### PR TITLE
Fix relative paths, again

### LINKED ISSUE #402: absolute and relative header paths aren't resolved to be the same header
When including "#pragma once" header twice, once in absolute path and once in relative paths, simplecpp doesn't resolve the header to be the same, and therefore includes it twice. Example:

`test.hh`:
```cpp
#pragma once

9
```

`test.cc`:
```
#include "test.hh"
#include "{YOUR_CURRENT_DIR_HERE}/test.hh"
```

`gcc -E` full output:
```cpp
# 1 "test.cc"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "test.cc"
# 1 "test.hh" 1


9
# 2 "test.cc" 2
```

`simplecpp` full output:
```cpp

#line 3 "test.hh"
9
#line 3 "{YOUR_CURRENT_DIR_HERE}/test.hh"
9
```

Thread: https://sourceforge.net/p/cppcheck/discussion/general/thread/c01f80556b/

### PR DESCRIPTION
**Pull request by Tal500**
Undo #415 , and hopefully finally fix the Windows string conversion error.
The windows string conversion part is based on https://gist.github.com/RyanJeong/04a4b92879ab10edfd9656d0aa4f3b77

Fixes #402

### CODE REVIEW

File: simplecpp.cpp [hunk 1]
```diff
@@ -2681,6 +2683,54 @@ static bool isCpp17OrLater(const simplecpp::DUI &dui)
...
+    static const std::string curdir = simplecpp::simplifyPath(currentDirectoryOSCalc());
+    return curdir;
+}
+
+static std::string toAbsolutePath(const std::string& path) {
+    if (path.empty()) {
+        return path;// preserve error file path that is indicated by an empty string
+    }
+    if (!isAbsolutePath(path)) {
+        return currentDirectory() + "/" + path;
```
Comment (danmar) [inline simplecpp.cpp:2718]: should we use simplifyPath here also maybe?  imagine that "path" is ".."?

Comment (Tal500) [reply simplecpp.cpp]: Done

**Comment by Tal500** [comment]
Note: See the compilation test for both UNICODE and non-UNICODE mode [at compiler explorer](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGErgBspK4AMngMmAByPgBGmMQgZqQADqgKhE4MHt6%2B/kGp6Y4CYRHRLHEJSXaYDplCBEzEBNk%2BflyBtpj2RQz1jQQlUbHxibYNTS257UEK4wPhQ%2BUjZgCUtqhexMjsHOYAzOHI3lgA1OZmCAQEyQogAPR3xEwA7gB0wIQIXjFeSluyjAIrzQLDuABUxABWDQaO7pFjJezJZJ3TBMDQBMwAdnQXGhkhhAUhe0hAE5IUwqAAOKnILAaLGUphSTBUJjIcmkuF4BFI5KvBDnEwaACC%2B0Ox0wZzMFyuN3ujxe70%2B31%2B8TQgkBwNQoIhtGhsPhiJqyNR6MxOLxGgJGOJZIp1Np9MZbJZbI5ZO5vJN/OQyPOHDWtE4kN4fg4WlIqE4bms1hOCg2Wyl%2Bx4pAImkDawA1iACa9IZJSVTSVIqZJAjSgsGOJIw5mo5xeLcNOnM2s4LAYIgUDrknR4uRKCD%2B/QEgA3P3JAD6464pOnewXADUhFwsdOF40WAFpDRaAR4rcIDEGzFwo0AJ6cNPn5jES8AeRi2hqGe4vBBbEEj4YtGvEa8FgPzAG4Yi0LcH6kFgLCGMA4iAdBeDEG%2BeDjpgkGRpgqg1F4h43rw4SHjWka0HgMRPA%2BHhYA2BDEDyDbocQMRpJgAAimCwUYZFGO2fAGMACjLngmDPI%2BySMARMiCCIYjsFI0nyEoagNroXD6HBKBxpY%2BjkbckBrKgyQ9JBcIEOgWmWNYUgnAAtGxciRAAkm4j5sdgdlsdOjkuW52C8KgTH0Vg%2BkQGs1S1M4ECuJMbTBAw6CDGUFR6AUGQCLFqVpOlDBJcMCTqRFPR9BMnitHoRV1HMeVLAVYz9JlhXVQsyUjFw4VJtsEhBiG9aIdGHAnNuu4nCwCiTicc6kq8S4nKu66vKSJwQLghAkNKeztbw75aCsOaJBorxYpCVIBBipYaKdkjSDWdakCwIDQqQ4aRgNzYgK2O2BqQnY9iOA5kBQED/WOICTsis7zouK5rhuW7EDue50IexDHqeiF3leUmYw%2Bz6vg4UlfoCv7/g2wFeKB4GQWmMFwQhkb4ChtToZhvDYbh%2BFQURXQNmRFFXtROyRnRDFQUxLFKBxXHweEoCAWsVACUJIliRJ4ZpvwMmiOICma0pKjqIhuhJAYvGmFZOl86FhnGZkpmzBZ5tWJYUgBUFeAhfA4VdKhUUxWVUzxYlLX5VlhSZI1KTZT0NUpYVPuRb0cyR5VAglfMpSh01DUB3Fsz9LHbUdZsXXtfovXPQ2A1DQjI1jRNU0zUt81Yoty2rUQxAbVtbby2sCBolgCRheXta8A9T0vQFTa2B9ve7ftJKvDCl0aHsVIkgEeySFvkKj3sfWvTPX0dt2v0QEgGzXHhQ7A32AORKwOyqKdtkjUccEnPOrxcMvbP4J3D2eg9ayR1nuWQigDaqT0M8J4yQCI9Q4KGSu/VOCPjwskPCJxUBUBrojUa41kCTW/rNFubcIAeARADbuKxtrtn2mYSQrxrqkj2NaAIVINDziJGYasnA7oT1bFPRsHB3qfT4ufS%2BGCb5AxBvER%2BbBODDUkAQhuJDm6w0Wv/NawVgGyFAfJcBghIEqSNqMWBTB4EfkQcg4RA10HXwINg3ByjVFEMbqQzRS0KH3zHBtVYdC%2B6kAHkwIelBEECMekIquM8WzzyzKQXMjDmFFjYTvTh3DIS8P3ofaeoj4l7VHmYXJIjAkL1IExdIzhJBAA%3D) (my best guess)

**Comment by danmar** [comment]
ok I try it out here: https://github.com/danmar/cppcheck/pull/7381

**Comment by danmar** [comment]
Well this does not work neither:

https://github.com/danmar/cppcheck/actions/runs/13923783226/job/38962964585?pr=7381

CI output:
```
       "D:\a\cppcheck\cppcheck\cppcheck.sln" (default target) (1) ->
       "D:\a\cppcheck\cppcheck\lib\cppcheck.vcxproj" (default target) (4) ->
       (ClCompile target) -> 
         D:\a\cppcheck\cppcheck\externals\simplecpp\simplecpp.cpp(152,13): error C2375: 'startsWith': redefinition; different linkage [D:\a\cppcheck\cppcheck\lib\cppcheck.vcxproj]
         D:\a\cppcheck\cppcheck\externals\simplecpp\simplecpp.cpp(2726,8): error C2264: 'startsWith': error in function definition or declaration; function not called [D:\a\cppcheck\cppcheck\lib\cppcheck.vcxproj]
```

**Comment by Tal500** [comment]
> @Tal500 I am sorry for slow reply.. hope you can fix it anyway.

On second glance, the problem seems to be very stupid. Microsoft MSVC complains about redefinition of a function even when one of them is defined to be with "static" visibility, when you do static linkage.
The solution is to stupidely add a postfix "_" to this function name of `startsWith()` to make all the compiling system happy (will do it now).

**Comment by danmar** [comment]
@Tal500 I tried this quickly. There is a testcase in cppcheck that fails:

https://github.com/danmar/cppcheck/actions/runs/14283167360/job/40035087732?pr=7381

The full CI message:
```

D:\a\cppcheck\cppcheck\test\testpreprocessor.cpp:2513(TestPreprocessor::testMissingIncludeCheckConfig): Assertion failed. 
Expected: 
test.c:1:0: information: Include file: \"missing.h\" not found. [missingInclude]\n
test.c:2:0: information: Include file: <header.h> not found. Please note: Cppcheck does not need standard library headers to get proper results. [missingIncludeSystem]\n
test.c:3:0: information: Include file: <missing2.h> not found. Please note: Cppcheck does not need standard library headers to get proper results. [missingIncludeSystem]\n
test.c:6:0: information: Include file: \"header4.h\" not found. [missingInclude]\n
test.c:9:0: information: Include file: \"D:\a\cppcheck\cppcheck/missing3.h\" not found. [missingInclude]\n
test.c:11:0: information: Include file: <D:\a\cppcheck\cppcheck/missing4.h> not found. Please note: Cppcheck does not need standard library headers to get proper results. [missingIncludeSystem]\n

Actual: 
test.c:1:0: information: Include file: \"missing.h\" not found. [missingInclude]\n
test.c:2:0: information: Include file: <header.h> not found. Please note: Cppcheck does not need standard library headers to get proper results. [missingIncludeSystem]\n
test.c:3:0: information: Include file: <missing2.h> not found. Please note: Cppcheck does not need standard library headers to get proper results. [missingIncludeSystem]\n
test.c:5:0: information: Include file: <header3.h> not found. Please note: Cppcheck does not need standard library headers to get proper results. [missingIncludeSystem]\n
test.c:6:0: information: Include file: \"header4.h\" not found. [missingInclude]\n
test.c:9:0: information: Include file: \"D:\a\cppcheck\cppcheck/missing3.h\" not found. [missingInclude]\n
test.c:11:0: information: Include file: <D:\a\cppcheck\cppcheck/missing4.h> not found. Please note: Cppcheck does not need standard library headers to get proper results. [missingIncludeSystem]\n
```

So it seems there is a unwanted message:
```
test.c:5:0: information: Include file: <header3.h> not found. Please note: Cppcheck does not need standard library headers to get proper results. [missingIncludeSystem]\n
```

**Comment by danmar** [comment]
The selfchecks in the CI also fail but I am not sure if that is caused by these changes right now.

**Comment by danmar** [comment]
The test `TestPreprocessor::testMissingIncludeCheckConfig` sounds more like it should be done in simplecpp spontanously. Maybe the recently added pytest testing can test this.

**Comment by Tal500** [comment]
> @Tal500 I tried this quickly. There is a testcase in cppcheck that fails:
> 
> https://github.com/danmar/cppcheck/actions/runs/14283167360/job/40035087732?pr=7381
> 
> The full CI message:
> 
> ```
> 
> D:\a\cppcheck\cppcheck\test\testpreprocessor.cpp:2513(TestPreprocessor::testMissingIncludeCheckConfig): Assertion failed. 
> Expected: 
> test.c:1:0: information: Include file: \"missing.h\" not found. [missingInclude]\n
> test.c:2:0: information: Include file: <header.h> not found. Please note: Cppcheck does not need standard library headers to get proper results. [missingIncludeSystem]\n
> test.c:3:0: information: Include file: <missing2.h> not found. Please note: Cppcheck does not need standard library headers to get proper results. [missingIncludeSystem]\n
> test.c:6:0: information: Include file: \"header4.h\" not found. [missingInclude]\n
> test.c:9:0: information: Include file: \"D:\a\cppcheck\cppcheck/missing3.h\" not found. [missingInclude]\n
> test.c:11:0: information: Include file: <D:\a\cppcheck\cppcheck/missing4.h> not found. Please note: Cppcheck does not need standard library headers to get proper results. [missingIncludeSystem]\n
> 
> Actual: 
> test.c:1:0: information: Include file: \"missing.h\" not found. [missingInclude]\n
> test.c:2:0: information: Include file: <header.h> not found. Please note: Cppcheck does not need standard library headers to get proper results. [missingIncludeSystem]\n
> test.c:3:0: information: Include file: <missing2.h> not found. Please note: Cppcheck does not need standard library headers to get proper results. [missingIncludeSystem]\n
> test.c:5:0: information: Include file: <header3.h> not found. Please note: Cppcheck does not need standard library headers to get proper results. [missingIncludeSystem]\n
> test.c:6:0: information: Include file: \"header4.h\" not found. [missingInclude]\n
> test.c:9:0: information: Include file: \"D:\a\cppcheck\cppcheck/missing3.h\" not found. [missingInclude]\n
> test.c:11:0: information: Include file: <D:\a\cppcheck\cppcheck/missing4.h> not found. Please note: Cppcheck does not need standard library headers to get proper results. [missingIncludeSystem]\n
> ```
> 
> So it seems there is a unwanted message:
> 
> ```
> test.c:5:0: information: Include file: <header3.h> not found. Please note: Cppcheck does not need standard library headers to get proper results. [missingIncludeSystem]\n
> ```

I claim that the "valid" value there is WRONG and the "actual" string value is CORRECT. 
The missing header3 should be reported twice, independently, since the full path inclusion in "..." isn't the same as the inclusion of the missing header file by a "system" include within <...>, UNLESS the header is found and is resolved to the same path.

**Comment by Tal500** [comment]
> The test `TestPreprocessor::testMissingIncludeCheckConfig` sounds more like it should be done in simplecpp spontanously. Maybe the recently added pytest testing can test this.

It's a matter of taste. I do not mind to have a double coverage, one that checks within the library and one that checks the library within the usage.

**Comment by danmar** [comment]
> It's a matter of taste. I do not mind to have a double coverage, one that checks within the library and one that checks the library within the usage.

yeah I am not against that we have tests in cppcheck but it seems to me that we could test this directly in simplecpp.

**Comment by Tal500** [comment]
> > It's a matter of taste. I do not mind to have a double coverage, one that checks within the library and one that checks the library within the usage.
> 
> yeah I am not against that we have tests in cppcheck but it seems to me that we could test this directly in simplecpp also..

The test cases there seems to be redundant, you can then omit them at all.
If more test cases are needed in your opinion, we can work this out, but I prefer them not to be a blocker for this push, because the coverage is very high (and I claim that it checks effectively all the cases appearing in the cppcheck tests)

**Comment by danmar** [comment]
> I claim that the "valid" value there is WRONG and the "actual" string value is CORRECT. The missing header3 should be reported twice, independently, since the full path inclusion in "..." isn't the same as the inclusion of the missing header file by a "system" include within <...>, UNLESS the header is found and is resolved to the same path.

I am not sure am I missing something?

There is a file `system/header3.h`. We provide the include path `system`. And the code is:
```
#include <header3.h>
```
So we should find that shouldn't we?

**Comment by danmar** [comment]
This manual test is the same isn't it?
```
daniel@laptop:~/cppchecksolutions/cppcheck$ mkdir system
daniel@laptop:~/cppchecksolutions/cppcheck$ touch system/header3.h
daniel@laptop:~/cppchecksolutions/cppcheck$ echo "#include <header3.h>" > test.c
daniel@laptop:~/cppchecksolutions/cppcheck$ gcc -E -Isystem test.c
```
gcc does not complain about a missing header3.h file.

**Comment by danmar** [comment]
Thanks I will try it out again

**Comment by danmar** [comment]
CI is running now:
https://github.com/danmar/cppcheck/pull/7381

**Comment by Tal500** [comment]
> CI is running now: [danmar/cppcheck#7381](https://github.com/danmar/cppcheck/pull/7381)

Hi! Any update?

**Comment by danmar** [comment]
hmm.. there was additional selfcheck warnings in tinyxml and simplecpp. however I guess that might mean the files are analyzed more properly and it indicates that these changes are good..

**Comment by danmar** [comment]
@Tal500 could you please solve the issues here then I will merge this and try to upstream this again?

**Comment by danmar** [comment]
I tried to solve the merge conflict but I might have messed up :-(

**Comment by Tal500** [comment]
> I tried to solve the merge conflict but I might have messed up :-(

Seems just like we just need to properly set up Python again in the CI workflow.
Not next to a comupter right now, I'll try this in few hours or maybe on Sunday

**Comment by Tal500** [comment]
> @Tal500 could you please solve the issues here then I will merge this and try to upstream this again?

Fixed now

**Comment by Tal500** [comment]
Thank you!
