### PR TITLE
Fix #376: Member access on user-defined literal tokenized incorrectly

### LINKED ISSUE #376: Member access on user-defined literal tokenized incorrectly
https://trac.cppcheck.net/ticket/13181
~~~c++
struct A { double eps(double); };
A operator ""_a(long double);

void f() {
    double d = 1.23;

    if (d == 1.2_a.eps(.1)) {}

}
~~~
`1.2_a.eps` is one token.

### PR DESCRIPTION
**Pull request by ludviggunne**

### CODE REVIEW

**Comment by danmar** [comment]
Please create an issue.
Please create a test.

File: simplecpp.cpp [hunk 1]
```diff
@@ -1002,7 +1002,8 @@ void simplecpp::TokenList::combineOperators()
                 continue;
             }
             // float literals..
-            if (tok->previous && tok->previous->number && sameline(tok->previous, tok)) {
+            if (tok->previous && tok->previous->number && sameline(tok->previous, tok) && tok->previous->str().find('_', 0) == std::string::npos
+                && tok->previous->str().find('.', 0) == std::string::npos) {
```
Comment (danmar) [inline simplecpp.cpp:1006]: hmm `tok->previous->str().find('_', 0) == std::string::npos && tok->previous->str().find('.', 0) == std::string::npos` can be simplified to `tok->previous->str().find_first_of("._") == std::string::npos`
