### PR TITLE
Fix #334 Do not assert when source file is missing

### LINKED ISSUE #334: Do not assert when source file is missing
Executing simplecpp with a missing file cause assertion error. We should report some file not found error instead:

```
daniel@laptop:~/simplecpp$ ./simplecpp notexist.cpp 
simplecpp: simplecpp.cpp:388: FileStream::FileStream(const string&): Assertion `file != nullptr' failed. 
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by olabetskyi**

### CODE REVIEW

File: simplecpp.cpp [hunk 1]
```diff
@@ -385,7 +385,8 @@ class FileStream : public simplecpp::TokenList::Stream {
         , lastCh(0)
         , lastStatus(0)
     {
-        assert(file != nullptr);
+        if (file != nullptr)
```
Comment (danmar) [inline simplecpp.cpp:388]: I assume condition should be `file == nullptr`

File: simplecpp.cpp [hunk 2]
```diff
@@ -385,7 +385,8 @@ class FileStream : public simplecpp::TokenList::Stream {
...
+            throw simplecpp::Output::FILE_NOT_FOUND;
```
Comment (danmar) [inline simplecpp.cpp:389]: hmm typically throwing a class is prefered. maybe in the short term this enum will work well.. this is not a pattern we want to start using throughout the code I guess.

**Review by danmar — COMMENTED** [review]
I would think it should be relatively easy to unit test the `simplecpp::TokenList::TokenList` constructor

File: simplecpp.cpp [hunk 3]
```diff
@@ -442,8 +445,15 @@ simplecpp::TokenList::TokenList(std::istream &istr, std::vector<std::string> &fi
...
         : frontToken(nullptr), backToken(nullptr), files(filenames)
 {
-    FileStream stream(filename);
-    readfile(stream,filename,outputList);
+    try
+    {
+        FileStream stream(filename);
+        readfile(stream,filename,outputList);
+    }
+    catch(const simplecpp::Output e) // TODO handle extra type of errors
```
Comment (danmar) [inline simplecpp.cpp:453]: please catch by reference.

File: test.cpp [hunk 4]
```diff
@@ -2900,6 +2917,8 @@ int main(int argc, char **argv)
     TEST_CASE(tokenMacro4);
     TEST_CASE(tokenMacro5);
 
+    TEST_CASE(makeTokenListNoFile);
```
Comment (danmar) [inline test.cpp:2920]: hmm.. the test cases are ordered alphabetically more or less.. and I prefer to put related test cases together so somehow I would like to put this near some other test cases where we test the TokenList constructor..

I have the feeling that the "readfile_" tests are somewhat related. They test the raw parsing of a file I think. I suggest you change the name of this test to "readfile_file_not_found"

**Review by danmar — APPROVED** [review]
when ci is happy we can merge this
